repos:
- repo: https://github.com/timothycrosley/isort
  rev: 5.13.2
  hooks:
  - id: isort
    args: ["--profile", "black"]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.4
  hooks:
  - id: ruff
  - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    additional_dependencies: [types-requests]
