x-minio-environment: &minio-environment
  MINIO_ROOT_USER: miniouser
  AWS_ACCESS_KEY_ID: miniouser
  MINIO_ROOT_PASSWORD: miniopassword
  AWS_SECRET_ACCESS_KEY: miniopassword

services:
  minio:
    image: minio/minio:RELEASE.2024-06-11T03-13-30Z
    command: server /data --console-address ":9001" --quiet
    environment:
      <<: *minio-environment
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: curl --fail http://localhost:9001
      interval: 1s
      timeout: 1s
      retries: 3

  minio-sample-loader:
    image: minio/mc:RELEASE.2024-06-12T14-34-03Z
    entrypoint: /bin/bash /entrypoint.sh
    environment:
      <<: *minio-environment
    volumes:
      - "./minio/mc/entrypoint.sh:/entrypoint.sh:ro"
      - "./data/STAC/sample/data/:/stac/sample:ro"
    depends_on:
      minio:
        condition: service_healthy
    command: mc cp --recursive /stac/sample minio/stac

  sample-indexer:
    build:
      dockerfile: docker/indexer/Dockerfile
      context: .
    image: sparkgeo/stac_indexer
    environment:
      <<: *minio-environment
      stac_index_indexer_output_dir: /output
      stac_index_reader_s3_endpoint: http://minio:9000
    volumes:
      - "indexer-output:/output:rw"
      - "./stac_index/common/stac_index/common:/app/stac_index/common/stac_index/common:rw"
      - "./stac_index/reader/s3/stac_index/reader/s3:/app/stac_index/reader/s3/stac_index/reader/s3:rw"
      - "./stac_index/indexer/stac_index/indexer:/app/stac_index/indexer/stac_index/indexer:rw"
      - "./data/STAC/sample/index-config.json:/index-config.json:ro"
    command: "python -m stac_index.indexer.index /index-config.json"
    depends_on:
      minio-sample-loader:
        condition: service_completed_successfully

  minio-index-loader:
    image: minio/mc:RELEASE.2024-06-12T14-34-03Z
    entrypoint: /bin/bash /entrypoint.sh
    environment:
      <<: *minio-environment
    volumes:
      - "./minio/mc/entrypoint.sh:/entrypoint.sh:ro"
      - "indexer-output:/index:rw"
    depends_on:
      sample-indexer:
        condition: service_completed_successfully
    command: mc cp --recursive /index minio/index

  api:
    environment:
      <<: *minio-environment
      stac_api_indexed_parquet_index_source_uri: s3://index/index/parquet
      stac_index_reader_s3_endpoint: http://minio:9000
    depends_on:
      minio-index-loader:
        condition: service_completed_successfully

volumes:
  indexer-output:
