services:

  indexer:
    build:
      dockerfile: docker/indexer/Dockerfile
      context: .
    image: sparkgeo/stac_indexer
    environment:
      stac_index_indexer_output_dir: /output
      INDEX_ROOT_CATALOG_URI: /data/catalog.json
      INDEX_CONFIG_PATH: /index-config.json
    volumes:
      - indexer-output:/output:rw
      - ./data/STAC/sample/data:/data:ro
      - ./data/STAC/sample/index-config.json:/index-config.json:ro

  api:
    volumes:
      - ./data/STAC/sample/data:/data:ro
      - indexer-output:/index:ro
    environment:
      stac_api_indexed_index_manifest_uri: /index/manifest.json
    depends_on:
      indexer:
        condition: service_completed_successfully

volumes:
  indexer-output:
