services:
  api:
    build:
      dockerfile: docker/api/Dockerfile
      context: .
    image: sparkgeo/stac_fastapi_indexed
    environment:
      stac_api_indexed_parquet_index_source_url: s3://tchristian-stac-serverless-data/index/
      stac_api_indexed_token_jwt_secret: z6wpXGxDbG/l1mHjlUgnhp/VMkiSZUEDDdnIfrPpWfk=
      AWS_PROFILE: ${AWS_PROFILE:-not-set}
    volumes:
      - "~/.aws:/root/.aws:ro"
    ports:
      - "8123:8000"
    command: tail -f /dev/null