services:
  re-rooter:
    image: python:3.12-slim
    volumes:
      - "./data/STAC/re_root_stac.py:/re_root_stac.py:ro"
      - "./data/STAC/sample/data:/data:ro"
      - "re-rooted-stac-http:/output:rw"
    command: python -m re_root_stac /data/ http://fileserver:8001/stac/ --source_root /data --target_root /output --single_item_links

  fileserver:
    image: python:3.12-slim
    volumes:
      - "re-rooted-stac-http:/data/stac:ro"
    working_dir: /data
    ports:
      - "8001:8001"
    command: python -m http.server 8001
    depends_on:
      re-rooter:
        condition: service_completed_successfully
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8001' || exit 1
      interval: 1s
      timeout: 1s
      retries: 3

  indexer:
    build:
      dockerfile: docker/indexer/Dockerfile
      context: .
    image: sparkgeo/stac_indexer
    environment:
      INDEX_ROOT_CATALOG_URI: http://fileserver:8001/stac/catalog.json
      INDEX_CONFIG_PATH: /index-config.json
      INDEX_PUBLISH_PATH: /output
    volumes:
      - "indexer-output:/output:rw"
      - "./data/STAC/sample/index-config.json:/index-config.json:ro"
    depends_on:
      fileserver:
        condition: service_healthy

  api:
    volumes:
      - indexer-output:/index:ro
    environment:
      stac_api_indexed_index_manifest_uri: /index/manifest.json
    depends_on:
      indexer:
        condition: service_completed_successfully

volumes:
  re-rooted-stac-http:
  indexer-output:
