services:
  indexer:
    build:
      dockerfile: docker/indexer/Dockerfile
      context: .
    image: sparkgeo/stac_indexer
    environment:
      INDEX_ROOT_CATALOG_URI: ${root_catalog_uri}
      INDEX_CONFIG_PATH: /index-config.json
      INDEX_PUBLISH_PATH: /output
      INDEX_MANIFEST_JSON_URI: ${index_manifest_json_uri}
      AWS_ACCESS_KEY_ID:
      AWS_REGION:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
    volumes:
      - "${tmp_index_path:-indexer-output}:/output:rw"
      - "${tmp_index_config_path:-indexer-config-fallback}:/index-config.json:ro"

  api:
    volumes:
      - "${tmp_index_path:-indexer-output}:/index:ro"
    environment:
      stac_api_indexed_index_manifest_uri: /index/manifest.json
      AWS_ACCESS_KEY_ID:
      AWS_REGION:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
    depends_on:
      indexer:
        condition: service_completed_successfully

volumes:
  indexer-output:
  indexer-config-fallback:
