services:
  api:
    build:
      dockerfile: docker/api/Dockerfile
      context: .
    image: sparkgeo/stac_fastapi_indexed
    environment:
      stac_api_indexed_parquet_index_source_uri: s3://tchristian-stac-serverless-data/index/parquet/
      stac_api_indexed_token_jwt_secret: z6wpXGxDbG/l1mHjlUgnhp/VMkiSZUEDDdnIfrPpWfk= # random, not a secret
      stac_api_indexed_log_level: debug
      AWS_PROFILE: ${AWS_PROFILE:-not-set}
    volumes:
      - "~/.aws:/root/.aws:ro"
      - "./stac_index:/app/stac_index:rw"
      - "./stac_fastapi/indexed:/app/stac_fastapi/indexed:rw"
    healthcheck:
      test: curl --fail http://localhost/_mgmt/ping
      interval: 5s
      timeout: 1s
      retries: 50
    ports:
      - "8123:80"