services:
  api:
    build:
      dockerfile: docker/api/Dockerfile
      context: .
    image: sparkgeo/stac_fastapi_indexed
    environment:
      stac_api_indexed_parquet_index_source_url: s3://tchristian-stac-serverless-data/index/
      stac_api_indexed_token_jwt_secret: f2e8MDUYh8rxkx6GV5PNqp7NgKrbvwmFEPyxrJ+50K4= # random, not a secret
      stac_api_indexed_log_level: debug
      AWS_PROFILE: ${AWS_PROFILE:-not-set}
    volumes:
      - "~/.aws:/root/.aws:ro"
      - "./stac_index_common:/app/stac_index_common:rw"
      - "./stac_fastapi_indexed:/app/stac_fastapi_indexed:rw"
    healthcheck:
      test: curl --fail http://localhost/_mgmt/ping
      interval: 5s
      timeout: 1s
      retries: 50
    ports:
      - "8123:80"