[project]
name = "stac-index"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb~=1.1.3",
    "pydantic-settings", # don't specify a version, determined by stac-pydantic
    "shapely~=2.0.4",
    "stac-fastapi.types~=3.0.0a2",
    "stac-pydantic~=3.1.0",
    "boto3~=1.34.125",
    "aiohttp>=3.10.11",
]

[project.optional-dependencies]
dev = [
    "pre-commit>=4.1.0",
    "pytest~=8.2.2",
]

[tool.pytest.ini_options]
pythonpath = ["./src"]

[tool.setuptools]
packages = ["stac_index"]
package-dir = {"" = "src"}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"