name: Pull Request, Any Branch

on:
  pull_request:
    branches:
      - '**'

jobs:
  unit-test:
    name: Execute Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: scripts/dev-init.sh
      - name: Test
        run: scripts/tests/unit-test.sh
  smoke-test:
    name: Execute Smoke Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: scripts/tests/smoke-test.sh
  integration-test:
    name: Execute Integration Tests
    needs:
      - smoke-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: scripts/tests/integration-test.sh
